# NullTicket Backend - Railway Configuration
# Deployment: railway.app

# Environment Variables Required:
# - GROQ_API_KEY: Your Groq API key
# - DATABASE_URL: PostgreSQL connection string (auto-provided by Railway)
# - JWT_SECRET: Secret key for JWT tokens
# - SMTP_HOST: SMTP server host
# - SMTP_PORT: SMTP server port
# - SMTP_PASSWORD: axumfbsmcljzncxh
# - TWILIO_ACCOUNT_SID: Twilio account SID (optional)
# - TWILIO_AUTH_TOKEN: Twilio auth token (optional)
# - TWILIO_PHONE_NUMBER: Twilio phone number (optional)

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"
SMTP_USER = "nullpowergrid@gmail.com"
